---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
library(readxl)
library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: slideblue

.size80[**Today's Agenda**]

<br>

.size50[
1. Discuss paper structure

2. Select your strongest reasons for an outline
]

<br>

.center[.size40[
  Justin Leinaweaver (Spring 2022)
]]



---

class: middle, center, slideblue

.size60[**Who or what is currently the biggest international threat to the United States?**]

<br>
<br>

.size50[**For Today**]

.size50[Brainstorm 8-10 reasons you picked this answer.]

???

### Everybody ready to go with our assignment for today?

<br>

Before we dig into this we need to talk about the excellent advice in the Farrell (2010) reading!




---

class: middle, slidegreen

.size60[**Farrell's (2010) Writing Advice**]

--

<br>

.size40[1) Read the Requirements for the Assignment]

???

### What's the advice in the "read the requirements for the assignment" section?

(Make sure you are answering the question that was asked!)

- It is WAY harder than you think to write one paper to cover two separate class prompts. Also, technically plagiarism.

--

<br>

.size40[2) Avoid Data Dumps]

???

### What's the advice in the "avoid data dumps" section?

(You may know a lot of stuff about a topic, but "stuff" is not the same thing as an argument)

- In fact, a long litany of stuff typically undermines your argument because it is distracting and confusing.



--

<br>

.size40[3) Cut to the Chase]

???

### What's the advice in the "cut to the chase" section?

(Make sure your argument paper gets to making its argument from the get-go)
- No, "since the beginning of time" or "Webster's dictionary defines..."

(Focus your introduction on making three things clear:)
1. What is the question?
2. Why should we care?
3. What is your argument.

(Focus every paragraph on your argument!)
- No background for the sake of background



--

<br>

.size40[4) Organize, Organize, Organize]

???

### What's the advice in the "organize, organize, organize" section?

(SLIDE)



---

class: middle, slidegreen

.size60[**Farrell's (2010) Writing Advice**]

<br>

.size40[4) Organize, Organize, Organize

+ Macro Structure

+ Meso Structure

+ Micro Structure
]

???

### According to Farrell, what is a good macro structure?
(- Every paper should have a clear beginning, middle and end)

This is probably the basic advice you've been getting since grade school.
- Tell me what you're gonna tell me, tell me and tell me what you told me.

<br>

### How do you demonstrate in the outline that your macro structure is good?
(Differentiate the introduction from the body of the paper from the conclusion.)

<br>

### What is a good meso structure?
(- Each paragraph should build support for your argument.)
(- Each paragraph should focus on one main point.)
(- The point of each paragraph should build on that in the previous paragraph, and create the foundations of the next.)

<br>

In other words, your meso structure is taken care of if you clearly diagram your argument, premises to the conclusion, before you start writing.

The work you've done this week in building that diagram is the work you need to outline and write a well structured argument paper.

### Make sense?

<br>

### What is the exercise farrell proposes you use to check the meso structure of an argument paper?

(Every paper you read:)
1. Summarize each paragraph in one sentence.
2. Read the summary sentences only and the paper should both make sense AND build logically.

<br>

### What does it mean if you can't summarize the paragraph in one sentence?
(Paragraph is doing too much.)

<br>

I cannot emphasize this enough.
- You should do this every time you write a paper!

Check your meso structure.

An argument with a bad meso structure will NEVER be convincing.
- No amount of evidence and critical analysis can overcome this weakness.

A weak argument with an awesome meso structure CAN still be effective.
- The easier it is for the reader to follow the argument, the more likely they will be convinced.

### Does that make sense?

<br>

### What is a good micro structure?
(1. Sentences must be well constructed: Simple words, simple sentences, direct active language, no spelling or grammatical mistakes.)
(2. Each sentence should flow logically, from one to the next.)

<br>

### Any questions on the three types of structure Farrell describes?


---

class: middle, slidegreen

.size60[**Farrell's (2010) Writing Advice**]

.size40[
1. Read the Requirements for the Assignment

2. Avoid Data Dumps

3. Cut to the Chase

4. Organize, Organize, Organize

5. Exercises in Style
]

???

### Last one, 5. what's the advice in the "exercises in style" section?

(Use "simple, direct writing, which communicates its arguments and evidence as clearly and unambiguously as possible" p6)

- Use the active voice (subject acts upon its verb) not passive (subject is a recipient of a verb’s action)
- e.g. Israel is threatening to bomb Iranian nuclear facilities NOT Iranian nuclear facilities are under Israeli threat.

- Simple words are better than complex words
- prefer straightforward sentence structures to complex ones.


---

class: middle, center, slidegreen

.size60[**To be convincing an argument should be .textred[logical], .textred[clear], .textred[credible] and .textred[critical].**]

???

All of this good advice is, hopefully, represented by our class writing rubric.

Remember, our class writing rubric tells you that a convincing an argument should be logical, clear, credible and critical.




---

class: middle, slidegreen

.size50[**Convincing arguments...**]

.size40[
+ .textred[**Logical**] arguments support their conclusion with well specified premises.

+ .textred[**Clear**] arguments are easy to read & understand.

+ .textred[**Credible**] arguments use high quality evidence and include proper citations.

+ .textred[**Critical**] arguments acknowledge the limitations of our logic/evidence and address counter-arguments.
]

???

### As you are now working on the first paper, do you have any questions or need clarifications about our rubric?

<br>

I grade using this rubric.

Basically, I read your paper and then ask myself four questions.



---

class: middle, slidegreen

.size50[**Convincing arguments...**]

.size40[
+ .textred[**Logical**]: Do the premises support the conclusion?

+ .textred[**Clear**]: Is the paper easy to read and understand?

+ .textred[**Credible**]: Is there enough high quality evidence (cited using APA)?

+ .textred[**Critical**]: Does the paper address weaknesses in the argument (e.g. logic, evidence, consider counter-arguments)?
]

???

Might be a good series of questions to ask yourself before submitting.



---

class: middle, center, slideblue

.size60[**Who or what is currently the biggest international threat to the United States?**]

<br>
<br>

.size50[**For Today**]

.size50[Brainstorm 8-10 reasons you picked this answer.]

???

So, this is what everyone prepared for today.



---

class: middle, slidegreen

.size60[.center[**The "best" premises are...**]]

.size50[
1. Clear,

2. A complete idea (sentence),

3. Logically connected to the conclusion, and

4. Could be supported by evidence.
]

???

Keep in mind, not all premises are created equal.

HOWEVER, to be an actual premise in an argument each needs to be:

### Questions on this list of criteria?



---

class: middle, slideblue

.size50[.center[**Who or what is currently the biggest international threat to the United States?**]]

<br>

.size40[
1. Write your thesis statement across the top of a piece of paper:
    + "Therefore, the biggest current threat to the US is..."

2. Write your list of 8-10 reasons below the thesis.
]

???

As you do this, please keep the criteria for a good premise in mind!

These should be 8-10 complete sentences / ideas!

<br>

### Everybody ready?

Ok, now stand up and review everyone elses' argument diagrams.

Bring a pen and vote on the premises you think are strongests in each diagram.

Put a check mark next to the ones you think are strongest.

<br>

Ok, take a look at the votes.

Be sure to reflect on the results of this before moving to your next steps.



---

class: slideblue

.pull-left[

<br>
<br>
<br>

.size70[.center[**For Friday**]]

<br>
<br>

.size70[.center[**Draft an Outline**]]

]

.pull-right[

.size35[**Intro**]
.size30[
+ What is the question?
+ Why do we care?
+ Thesis statement
]

.size35[**Reason 1 (premise)**]
.size30[
+ Evidence x 2
]

.size35[**Reason 2 (premise)**]
.size30[
+ Evidence x 2
]

.size35[**Reason 3 (premise)**]
.size30[
+ Evidence x 2
]]


???

Your task for Friday is to build an outline of your argument with all of these elements INCLUDING two pieces of evidence for each premise

### Questions on the assignment?
