---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
library(readxl)
library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: slideblue

.size80[**Today's Agenda**]

<br>

.size50[
Review outlines and get ready to write the paper.
]

<br>

.center[.size40[
  Justin Leinaweaver (Spring 2022)
]]



---

class: slideblue

.pull-left[

<br>
<br>
<br>

.size70[.center[**For Today**]]

<br>
<br>

.size70[.center[**Draft an Outline**]]

]

.pull-right[

.size35[**Intro**]
.size30[
+ What is the question?
+ Why do we care?
+ Thesis statement
]

.size35[**Reason 1 (premise)**]
.size30[
+ Evidence x 2
]

.size35[**Reason 2 (premise)**]
.size30[
+ Evidence x 2
]

.size35[**Reason 3 (premise)**]
.size30[
+ Evidence x 2
]]




---

class: middle, slideblue

.size60[.center[**Review the Outlines in Pairs**]]

<br>

### Person 1: Present your outline and evidence
.size40[Explain each premise and why you believe the evidence is high quality enough for the purpose]

--

<br>

### Person 2: To be convincing to you...
.size40[
+ Is each premise clear enough?
+ Is each piece of evidence high enough quality?
]




---

class: middle, center, slideblue

.size60[**Who or what is currently the biggest international threat to the United States?**]

<br>
<br>

.size50[Reflect on the feedback, revise your outline and start writing!]



