---
format: revealjs
---

## Today's Agenda {background-image="Images/background-worldmap4.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**Review outlines and write the paper**
:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2026)
:::

::: notes
Prep for Class

1. Check submissions on Canvas
    - Review and give feedback during class
    
<br>

REFLECTIONS SP24

- This went GREAT today with a couple tweaks
- Class focused most of their time in only one pairing
- You made them work for 15 minutes on ONLY the first paper. Force them to push through and keep working on one paper. Make sure the person has a counter for every premise! THEN swap.

:::



## For Today {background-image="Images/background-worldmap4.png" .center .smaller}

::::: {.columns}
:::: {.column width="40%"}

<br>

<br>

<br>

::: {.r-fit-text}
**Paper 1 Outline**
:::
::::

:::: {.column width="10%"}

::::

:::: {.column width="50%"}
**Intro**

- What is the question?
- Why do we care about the question?
- Thesis statement

**Reason 1 (premise)**

- Evidence x 2

**Reason 2 (premise)**

- Evidence x 2

**Reason 3 (premise)**

- Evidence x 2
::::
:::::

::: notes
**Everybody ready to go with this?**

- **Outline in hand?**

<br>

Ok, time to get some feedback!

- Today you will get feedback from two people and have a chance to revise your outline to reflect that feedback.

- In a moment I'll split you into pairs...

<br>

**SLIDE**: Plan of attack!
:::



## Review the Outlines in Pairs {background-image="Images/background-worldmap4.png" .center}

<br>

::: {.r-fit-text}

**Person 1: Present your Outline**

- What is the question? 

- Why do we care about the question?

- Thesis

- Each premise with evidence

:::

::: notes

Person 1: Walk the other person through the outline of your paper

- Sell them on your introduction, then

- Explain each premise AND how the evidence supports it

<br>

**Make sense?**

<br>

**SLIDE**: Person 2's job

:::



## Review the Outlines in Pairs {background-image="Images/background-worldmap4.png" .center}

<br>

::: {.r-fit-text}

**Person 2: Is the paper convincing?**

- Does the introduction draw you into the paper?

- Is each premise clear?

- Is the evidence sufficiently high quality?

- Is this a strong inductive argument?

:::

::: notes

Person 2's job is to make sure your outline sets up a convincing argument

<br>

Does the introduction draw you into the paper?

- Do you understand the question and why it matters?

- Is the thesis clear?

<br>

Is each premise clear and supported by high quality evidence?

<br>

Is this a strong inductive argument?

- Meaning if we accept the premises as true, is it more likely that the conclusion is true?

<br>

**Make sense?**

<br>

**SLIDE**: That's all the expected stuff, but you also have one additional job

:::



## Review the Outlines in Pairs {background-image="Images/background-worldmap4.png" .center}

<br>

::: {.r-fit-text}

**Person 2: Is the paper convincing?**

- Does the introduction draw you into the paper?

- Is each premise clear?

- Is the evidence sufficiently high quality?

- Is this a strong inductive argument?

- **Design a counter-argument for this paper**

:::

::: notes

According to the grading rubric, a convincing argument paper MUST include critical analysis!

- There are a ton of ways to add critical analysis to a paper, but for our exercise I will ask each of you to include a counter-argument paragraph

- By that I mean, an alternative answer to the question that you present IN ITS STRONGEST FORM, and then address

- e.g. explain why this strong answer doesn't replace your answer

<br>

Your paper offers three premises or reasons your chosen event is the most important

- A compelling counter-argument should use those exact same criteria!

- If you tell the reader that economic impacts make your event most important, then other events with large economic impacts must also be important

- If you tell the reader threats to human life are important, then other events with large death counts are also important

- **Make sense?**

<br>

So, pairs, your final job today is to help each other brainstorm a counter-argument for each others' papers

- I am asking you to come up with an alternative "most important event" that would make a good counter for your specific paper

<br>

**Questions on the task?**

- Let's go!

<br>

*FOR YOU, SAVE TIME TO DO THIS EXERCISE 2x*
:::



## Revise your Outline {background-image="Images/background-worldmap4.png" .center}

<br>

**Intro**

**Premise 1** (with evidence)

**Premise 2** (with evidence)

**Premise 3** (with evidence)

**Counter-Argument**

**Conclusion**

::: notes

Now that you've heard some more arguments and gotten feedback on yours it's time to revise.

<br>

Reflect on the feedback, revise your outline and start writing!

- Tighten up those premises

- Add a counter-argument paragraph

<br>

Essentially I'm looking for a six paragraph paper

- e.g. introduction, premise 1, 2, 3, counter-argument and conclusion

<br>

**SLIDE**: Assignment for next class

:::



## {background-image="Images/13_3-dr-strangelove.jpg"}

[**For Next Class:**]{style="color:white;"}

- [Read Waltz (1988) on neorealism]{style="color:white;"}

::: notes

*Also funny: 03_3-Realism1.jpg*

<br>

The paper is due at the end of next week!

<br>

In the meantime, next week we shift our focus into Section 2 of the class

- We need theories to help us understand: Why do wars happen?

:::




## SLIDES for SPRING TERMS



## For Next Class {background-image="Images/background-worldmap4.png" .center}

<br>

Submit a REVISED outline of your first paper

- Same requirements as before, and

- Add a counter-argument paragraph outline (details on Canvas)




::: notes

Paper is due at the end of next week!

<br>

Counter-Argument

- Describe the alternative international political event
- What is the strongest argument you can make that this is "most" important?
- Why does that argument not change the thesis of your paper?


:::




