---
format: revealjs
---


## Today's Agenda {background-image="Images/background-worldmap4.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
library(kableExtra)
```

<br>

::: {.r-fit-text}

**Paper 1: Writing Workshop**

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2026)
:::

::: notes
Prep for Class

1. Review Canvas submissions

2. They are not mature enough to be productive in a writing workshop, you have to steer the ship. You give them prompts then go around the room (you too!) reading and giving feedback!
    
<br>

**SLIDE**: Today we work on the papers which are due on Friday

:::




## Paper 1 {background-image="Images/background-worldmap4.png" .center}

<br>

What is the most important international political event to occur in the last six months?

- Your selected event must be framed as a specific actor taking a specific action against a specific target. 

::: notes

**Any questions on the prompt or my expectations?**

<br>

**SLIDE**: Let's do some writing!

:::



## {background-image="Images/background-worldmap4.png" .center}

::: {.r-fit-text}
**Write your Introduction**

- What is the question?

- Why is the question important? (with evidence)

- Thesis statement
:::

::: notes

I'm going to give you ten minutes to write your introduction paragraph

- Make sure it nails these three elements

<br>

Ok, go read each other's introductions.

- Does it grab your attention?

- Does it make the thesis clear?

<br>

**SLIDE**: On to the counter argument

:::



## {background-image="Images/background-worldmap4.png" .center}

**Building your Counter Argument**

- What is the alternative?

- Strongest reasons it is "most important"? (with evidence)

- Why doesn't this change your thesis?

::: notes

Now, take 10 minutes to write your counter-argument paragraph

<br>

Read and give feedback

<br>

**SLIDE**: Alright, workshop time, keep going!

:::




## Revise your Outline {background-image="Images/background-worldmap4.png" .smaller}

**Intro**

- What is the question?
- Why is the question important?
- Thesis statement: Theory X is most useful because...

**Premise 1: Theory 1 is most useful because... (with evidence)**

**Premise 2: Theory 1 is most useful because... (with evidence)**

**Premise 3: Theory 1 is most useful because... (with evidence)**

**Counter-Argument: Theory 2**

- What is the strongest alternative?
- Why does it not change your position?

::: notes

**SLIDE**: Assignment for next class

:::



## For Next Class  {background-image="Images/background-worldmap4.png" .center}

<br>

Kenneth N. Waltz. (1988). The Origins of War in Neorealist Theory. *The Journal of Interdisciplinary History*. Vol. 18, No. 4, pp. 615-628

- Read p615-620 and skim the rest

- What is Waltz's answer to the question of why wars happen?

::: notes

:::





