---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
library(readxl)
library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: slideblue

.size80[**Today's Agenda**]

<br>

.size50[
.center[
Writing Workshop
]
]

<br>

.center[.size40[
  Justin Leinaweaver (Spring 2022)
]]

???

## Prep for Class
1. ...

<br>

* Opening Discussion *

ANYTHING INTERESTING GOING ON IN WORLD POLITICS AT THE MOMENT?






---

class: middle, center, slideblue

.size60[**Who or what is currently the biggest international threat to the United States?**]

???

The prompt for your paper.

QUESTIONS?



---

class: middle, slidegreen

.size60[**Farrell's (2010) Writing Advice**]

.size40[
1. Read the Requirements for the Assignment

2. Avoid Data Dumps

3. Cut to the Chase

4. Organize, Organize, Organize

5. Exercises in Style
]

???

QUESTIONS ON FARRELL'S ADVICE?



---

class: middle, center, slidegreen

.size60[**To be convincing an argument should be .textred[logical], .textred[clear], .textred[credible] and .textred[critical].**]


---

class: middle, slidegreen

.size50[**Convincing arguments...**]

.size40[
+ .textred[**Logical**]: Do the premises support the conclusion?

+ .textred[**Clear**]: Is the paper easy to read and understand?

+ .textred[**Credible**]: Is there enough high quality evidence (cited using APA)?

+ .textred[**Critical**]: Does the paper address weaknesses in the argument (e.g. logic, evidence, consider counter-arguments)?
]
