---
format: revealjs
---


## Today's Agenda {background-image="Images/background-worldmap4.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
library(kableExtra)
```

<br>

**III. Why is it so Hard to Cooperate with Other Countries?**

- Review outlines and write the paper

<br>

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. In getting them tready to give each other feedback on the outlines make sure to emphasize that each theory must be explained (with source citation) BEFORE application 
:::




## For Today: Draft an Outline {background-image="Images/background-worldmap4.png" .smaller}

**Intro**

- What is the question?
- Why is the question important?
- Thesis statement: Theory X is most useful because...

**Premise 1: Theory 1 is most useful because... (with evidence)**

**Premise 2: Theory 1 is most useful because... (with evidence)**

**Premise 3: Theory 1 is most useful because... (with evidence)**

**Counter-Argument: Theory 2**

- What are the strengths of this explanation?
- What are the weaknesses of this explanation?
- Why is it not ultimately more useful than Theory 1?

::: notes
**Everybody ready to go with this?**

- **Outline in hand?**

<br>

Ok, time to get some feedback!

Today you will get feedback from two people and have a chance to revise your outline to reflect that feedback.

In a moment I'll split you into pairs...
:::



## Review the Outlines in Pairs {background-image="Images/background-worldmap4.png" .center}

<br>

**Person 1: Present your Outline**

::: notes
Person 1 presents their paper outline
:::



## Review the Outlines in Pairs {background-image="Images/background-worldmap4.png" .center}

<br>

**Person 1: Present your Outline**

**Person 2: To be convincing to you...**

+ Is EACH theory applied correctly?

+ Is EACH theory evaluated using the same criteria?

+ What evidence is needed to support this evaluation?

::: notes
**Person 2 gives feedback focused on helping person 1 make it more convincing**

<br>

This criteria piece is new

- Two key elements to make this a coherent argument paper

1. A strong thesis statement that carries through the whole paper, and

2. Each theory should be evaluated using the same criteria
    - Need this to tie all the pieces together clearly.

### Questions on this?
 
<br>

*YOU:* Make sure to do this 2x!
:::


## Revise your Outline {background-image="Images/background-worldmap4.png" .smaller}

**Intro**

- What is the question?
- Why is the question important?
- Thesis statement: Theory X is most useful because...

**Premise 1: Theory 1 is most useful because... (with evidence)**

**Premise 2: Theory 1 is most useful because... (with evidence)**

**Premise 3: Theory 1 is most useful because... (with evidence)**

**Counter-Argument: Theory 2**

- What are the strengths of this explanation?
- What are the weaknesses of this explanation?
- Why is it not ultimately more useful than Theory 1?

::: notes
Now that you've heard some more arguments and gotten feedback on yours it's time to revise.

- Reflect on the feedback, revise your outline and start writing!

- Tighten up those premises

<br>

### Why don't we need a counter-argument paragraph here?

- (Critical analysis through the whole thing!)

<br>

Paper is due next week!
:::