---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
library(readxl)
library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: slideblue

.size80[**Today's Agenda**]

<br>

.size50[
Select your strongest reasons for an outline
]

<br>

.center[.size40[
  Justin Leinaweaver (Spring 2022)
]]

???

## Prep for Class
1. ...

<br>

### Current events check-in!


---

class: middle, center, slideblue

.size60[**Should the US use force (military or economic) to compel other states to behave in line with our interests?**]

<br>
<br>

.size50[**For Today**]

.size50[Brainstorm 8-10 reasons you picked this answer.]

???

### Everybody ready to go with our assignment for today?

<br>

Before we dig into this let's refresh our memories on the excellent advice in the Farrell (2010) reading!




---

class: middle, slidegreen

.size60[**Farrell's (2010) Writing Advice**]

.size40[
1. Read the Requirements for the Assignment

2. Avoid Data Dumps

3. Cut to the Chase

4. Organize, Organize, Organize

5. Exercises in Style
]

???

### Any questions on these sections / pieces of advice?

(Sec 1: Make sure you are answering the question that was asked!)

(Sec 2: You may know a lot of stuff about a topic, but "stuff" is not the same thing as an argument)

(Sec 3: Make sure your argument paper gets to making its argument from the get-go)

(Focus your introduction on making three things clear:)
1. What is the question?
2. Why should we care?
3. What is your argument.

(Focus every paragraph on your argument!)
- No background for the sake of background

(Sec 4: Macro, Meso and Micro Structures)

(Sec 5: Use "simple, direct writing, which communicates its arguments and evidence as clearly and unambiguously as possible" p6)



---

class: middle, center, slidegreen

.size60[**To be convincing an argument should be .textred[logical], .textred[clear], .textred[credible] and .textred[critical].**]

???

All of this good advice is, hopefully, represented by our class writing rubric.

Remember, our class writing rubric tells you that a convincing an argument should be logical, clear, credible and critical.




---

class: middle, slidegreen

.size50[**Convincing arguments...**]

.size40[
+ .textred[**Logical**]: Do the premises support the conclusion?

+ .textred[**Clear**]: Is the paper easy to read and understand?

+ .textred[**Credible**]: Is there enough high quality evidence (cited using APA)?

+ .textred[**Critical**]: Does the paper address weaknesses in the argument (e.g. logic, evidence, consider counter-arguments)?
]

???

### As you are now working on the second paper, do you have any questions or need clarifications about our rubric?

<br>

I grade using this rubric.

Basically, I read your paper and then ask myself four questions.




---

class: middle, center, slideblue

.size60[**Should the US use force (military or economic) to compel other states to behave in line with our interests?**]

<br>
<br>

.size50[**For Today**]

.size50[Brainstorm 8-10 reasons you picked this answer.]

???

So, this is what everyone prepared for today.



---

class: middle, slidegreen

.size60[.center[**The "best" premises are...**]]

.size50[
1. Clear,

2. A complete idea (sentence),

3. Logically connected to the conclusion, and

4. Could be supported by evidence.
]

???

Keep in mind, not all premises are created equal.

HOWEVER, to be an actual premise in an argument each needs to be:

### Questions on this list of criteria?



---

class: middle, slideblue

.size50[.center[**Should the US use force (military or economic) to compel other states to behave in line with our interests?**]]

<br>

.size40[
1. Write your thesis statement across the top of a piece of paper:
    + "Therefore, the US should / should not use force..."

2. Write your list of 8-10 reasons below the thesis.
]

???

As you do this, please keep the criteria for a good premise in mind!

These should be 8-10 complete sentences / ideas!

<br>

### Everybody ready?

Ok, now stand up and review everyone elses' argument diagrams.

Bring a pen and vote on the premises you think are strongests in each diagram.

Put a check mark next to the ones you think are strongest.

<br>

Ok, take a look at the votes.

Be sure to reflect on the results of this before moving to your next steps.



---

class: slideblue

.pull-left[

<br>
<br>
<br>

.size70[.center[**For Friday**]]

<br>
<br>

.size70[.center[**Draft an Outline**]]

]

.pull-right[

.size35[**Intro**]
.size30[
+ What is the question?
+ Why do we care?
+ Thesis statement
]

.size35[**Reason 1 (premise)**]
.size30[
+ Evidence x 2
]

.size35[**Reason 2 (premise)**]
.size30[
+ Evidence x 2
]

.size35[**Reason 3 (premise)**]
.size30[
+ Evidence x 2
]]


???

Your task for Friday is to build an outline of your argument with all of these elements INCLUDING two pieces of evidence for each premise

### Questions on the assignment?
