---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
library(readxl)
library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: slideblue

.size70[**Today's Agenda**]

<br>

.size40[

Bhambra, G., Bouka, Y., Persaud, R., Rutazibwa, O., Thakur, V., Bell, D., Smith, K., Haastrup, T. and Adem, S. (2020, Jul 3). Why Is Mainstream International Relations Blind to Racism? *Foreign Policy*.

]

<br>
<br>

.center[.size40[
  Justin Leinaweaver (Spring 2022)
]]

???

## Prep for Class

1. 





---

class: slidegreen, middle

.size60[**Assignment for Monday**]

.size40[
Bring to class a piece of evidence describing a .textred[private individual] impacting international politics in a .textred[measurable] and .textred[significant] way.

Note: We are looking for people like us so skip the examples that depend on personal wealth or brilliant new inventions.
]

???

Assignment for Monday

Bring to class a piece of evidence describing a private individual impacting international politics in a measurable and significant way.

Note: We are looking for people like us so skip the examples that depend on personal wealth or brilliant new inventions.

Submit your evidence to the Google Drive sheet in yor email.

Try not to overlap!