---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
library(readxl)
library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: slideblue

.size70[**Today's Agenda**]

<br>

.size40[

Bring to class a current event that will allow us to continue exploring the role of race in international political events.

]

<br>
<br>

.center[.size40[
  Justin Leinaweaver (Spring 2022)
]]

???

## Prep for Class

1. 



---

class: slidegreen, middle

.size60[**Assignment for Monday**]

.size45[
Bring to class a recent international political event we have not explored in class. 

Find something you think is interesting and be ready to explain to the class why you picked it.
]

???

Assignment for Monday

Bring to class a recent international political event we have not explored in class. Find something you think is interesting and be ready to explain to the class why you picked it.

Submit your evidence to the Google Drive sheet in yor email.

Try not to overlap!